### ISSUE TITLE
"Spoil" problem in PDF output for CYOA ebooks

### ISSUE THREAD

**Issue by akelai** [farvardin/textallion#2]
In the "Livre-jeu" PDF example provided in the [project website](http://anamnese.online.fr/site2/textallion/showcase/the_blue_death/), I see "spoil" happening: the reader is exposed to parts of content that are outside the target content of choice.

Can this problem be avoided in some way?

**Comment by akelai** [comment]
(Reply to myself): use page breaks before and after any target section: `{/...}`

**Comment by farvardin** [comment]
@akelai

The PDF output is meant to give an output close to a traditional gamebook like "choose your own adventure" / "livre dont vous êtes le héros". See http://www.le-gobelin-rose.com/wp-content/uploads/2016/03/LDVELH-le-sorcier-de-la-montagne-de-feu-4.png

You can use individual page break, but there are two other simpler solutions (or at least less tedious):

- Inside your document: just add this in the header:

```
%!postproc(tex): '\\hypertarget' '\\newpage \\hypertarget'
```

(there is an anchor ("hypertarger" in latex) before every heading, so it will automatically add a newpage break)

- Inside the .sty style file, in the sample it will be includes/sample_cyoa.sty, if you create a new project from the command like it will copy the the template to a "your_project_name.sty" file. Just find the "\def\PAGExSUBxBREAKxPOLICY{2} " and replace 2 by 4 (which will break at every paragraph)
